// Audit Log / Activity Trail (Component 7) — mock events for 0G-archived audit trail.
// Each event is verifiable on-chain and/or in 0G Storage. Sora trust mech #3:
// "każdą decyzja Council jest weryfikowalna na zewnatrz".
//
// Event types: ProposalCreated | AgentVoted | VerdictReached | MultisigSigned |
//              OnchainExecuted | RulesUpdated | AgentAdded | AgentReputationChanged |
//              RulesProposed | TimelockQueued

const AUDIT_EVENTS = [
  {
    id: 'evt-187',
    type: 'OnchainExecuted',
    timestamp: '2026-05-02T16:22:14Z',
    relativeTime: '12 min ago',
    actor: { kind: 'multisig', label: 'Treasury Multisig', ens: 'treasury.aicouncil.eth' },
    title: 'PROP-042 executed on Base',
    summary: 'Allocated 100,000 USDC to Aave v3 USDC supply',
    delta: { kind: 'amount', value: 100000, asset: 'USDC', direction: 'out' },
    txHash: '0x8a3f...e21c',
    txUrl: 'https://sepolia.basescan.org/tx/0x8a3f...e21c',
    cid: 'bafy...prop042-exec',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-exec',
    block: 12_487_321,
    gas: '184,221',
  },
  {
    id: 'evt-186',
    type: 'TimelockQueued',
    timestamp: '2026-05-02T16:18:02Z',
    relativeTime: '16 min ago',
    actor: { kind: 'multisig', label: 'Treasury Multisig', ens: 'treasury.aicouncil.eth' },
    title: 'PROP-042 queued in Timelock',
    summary: '48h delay until execution. Cancellable by 5-of-7 multisig.',
    delta: { kind: 'duration', value: '48h' },
    txHash: '0x7b22...c4e1',
    txUrl: 'https://sepolia.basescan.org/tx/0x7b22...c4e1',
    cid: 'bafy...prop042-queue',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-queue',
    block: 12_487_198,
  },
  {
    id: 'evt-185',
    type: 'MultisigSigned',
    timestamp: '2026-05-02T16:14:30Z',
    relativeTime: '20 min ago',
    actor: { kind: 'wallet', label: 'maxima.aicouncil.eth', ens: 'maxima.aicouncil.eth' },
    title: 'Multisig signature 3/3 collected',
    summary: 'Threshold reached. Ready to queue for execution.',
    delta: { kind: 'count', value: '3/3' },
    txHash: null,
    cid: 'bafy...prop042-sig3',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-sig3',
  },
  {
    id: 'evt-184',
    type: 'MultisigSigned',
    timestamp: '2026-05-02T16:11:08Z',
    relativeTime: '23 min ago',
    actor: { kind: 'wallet', label: 'pico.aicouncil.eth', ens: 'pico.aicouncil.eth' },
    title: 'Multisig signature 2/3',
    summary: 'Second signer approved.',
    delta: { kind: 'count', value: '2/3' },
    cid: 'bafy...prop042-sig2',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-sig2',
  },
  {
    id: 'evt-183',
    type: 'MultisigSigned',
    timestamp: '2026-05-02T16:08:44Z',
    relativeTime: '26 min ago',
    actor: { kind: 'wallet', label: 'atlas.aicouncil.eth', ens: 'atlas.aicouncil.eth' },
    title: 'Multisig signature 1/3',
    summary: 'First signer approved verdict.',
    delta: { kind: 'count', value: '1/3' },
    cid: 'bafy...prop042-sig1',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-sig1',
  },
  {
    id: 'evt-182',
    type: 'VerdictReached',
    timestamp: '2026-05-02T16:04:22Z',
    relativeTime: '30 min ago',
    actor: { kind: 'council', label: 'Council', ens: 'council.aicouncil.eth' },
    title: 'PROP-042 verdict: PASSED',
    summary: '4 FOR, 0 AGAINST, 1 ABSTAIN. Quorum met. Confidence 78%.',
    delta: { kind: 'verdict', value: 'PASSED' },
    cid: 'bafy...prop042-verdict',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-verdict',
  },
  {
    id: 'evt-181',
    type: 'AgentVoted',
    timestamp: '2026-05-02T16:03:51Z',
    relativeTime: '31 min ago',
    actor: { kind: 'agent', label: 'Sentiment', ens: 'sentiment.aicouncil.eth', agentId: 'sentiment' },
    title: 'Agent voted ABSTAIN',
    summary: 'Confidence 52%. Conceded to risk + tech reads.',
    delta: { kind: 'vote', value: 'ABSTAIN', conf: 0.52 },
    cid: 'bafy...prop042-vote-sentiment',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-vote-sentiment',
  },
  {
    id: 'evt-180',
    type: 'AgentVoted',
    timestamp: '2026-05-02T16:03:38Z',
    relativeTime: '31 min ago',
    actor: { kind: 'agent', label: 'Tech', ens: 'tech.aicouncil.eth', agentId: 'tech' },
    title: 'Agent voted FOR',
    summary: 'Confidence 78%. Aave v3.0.2 audit + clean integration.',
    delta: { kind: 'vote', value: 'FOR', conf: 0.78 },
    cid: 'bafy...prop042-vote-tech',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-vote-tech',
  },
  {
    id: 'evt-179',
    type: 'AgentVoted',
    timestamp: '2026-05-02T16:03:24Z',
    relativeTime: '31 min ago',
    actor: { kind: 'agent', label: 'Risk', ens: 'risk.aicouncil.eth', agentId: 'risk' },
    title: 'Agent voted FOR',
    summary: 'Confidence 66%. VaR(95) bounded at 1,840 USDC. HITL waiver required.',
    delta: { kind: 'vote', value: 'FOR', conf: 0.66 },
    cid: 'bafy...prop042-vote-risk',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-vote-risk',
  },
  {
    id: 'evt-178',
    type: 'AgentVoted',
    timestamp: '2026-05-02T16:03:09Z',
    relativeTime: '31 min ago',
    actor: { kind: 'agent', label: 'Bear', ens: 'bear.aicouncil.eth', agentId: 'bear' },
    title: 'Agent voted FOR',
    summary: 'Confidence 71%. Conceded after counter-arg addressed.',
    delta: { kind: 'vote', value: 'FOR', conf: 0.71 },
    cid: 'bafy...prop042-vote-bear',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-vote-bear',
  },
  {
    id: 'evt-177',
    type: 'AgentVoted',
    timestamp: '2026-05-02T16:02:55Z',
    relativeTime: '32 min ago',
    actor: { kind: 'agent', label: 'Bull', ens: 'bull.aicouncil.eth', agentId: 'bull' },
    title: 'Agent voted FOR',
    summary: 'Confidence 84%. APY 3.9-4.6% range, exit liquidity tested.',
    delta: { kind: 'vote', value: 'FOR', conf: 0.84 },
    cid: 'bafy...prop042-vote-bull',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-vote-bull',
  },
  {
    id: 'evt-176',
    type: 'ProposalCreated',
    timestamp: '2026-05-02T15:42:11Z',
    relativeTime: '52 min ago',
    actor: { kind: 'wallet', label: 'dan.aicouncil.eth', ens: 'dan.aicouncil.eth' },
    title: 'Proposal PROP-042 submitted',
    summary: 'Allocate 100k USDC to Aave v3 USDC supply for 4.2% est. APY',
    delta: { kind: 'amount', value: 100000, asset: 'USDC' },
    txHash: '0x4f81...a209',
    txUrl: 'https://sepolia.basescan.org/tx/0x4f81...a209',
    cid: 'bafy...prop042-create',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop042-create',
    block: 12_486_722,
  },
  {
    id: 'evt-175',
    type: 'AgentReputationChanged',
    timestamp: '2026-05-02T14:18:33Z',
    relativeTime: '2h ago',
    actor: { kind: 'system', label: 'Reputation Engine', ens: 'rep.aicouncil.eth' },
    title: 'Risk agent reputation +0.4',
    summary: 'PROP-039 outcome confirmed Risk\'s VaR estimate. Trust score 90.6 → 91.0.',
    delta: { kind: 'reputation', value: '+0.4', agentId: 'risk' },
    cid: 'bafy...rep-risk-2026-05-02',
    cidUrl: 'https://0g.ai/storage/cid/bafy...rep-risk-2026-05-02',
  },
  {
    id: 'evt-174',
    type: 'OnchainExecuted',
    timestamp: '2026-05-02T11:04:18Z',
    relativeTime: '5h ago',
    actor: { kind: 'multisig', label: 'Treasury Multisig', ens: 'treasury.aicouncil.eth' },
    title: 'PROP-039 executed',
    summary: 'Withdrew 25k USDC from Compound v3, redeposit to Morpho Blue',
    delta: { kind: 'amount', value: 25000, asset: 'USDC', direction: 'rotate' },
    txHash: '0x12cd...8742',
    txUrl: 'https://sepolia.basescan.org/tx/0x12cd...8742',
    cid: 'bafy...prop039-exec',
    cidUrl: 'https://0g.ai/storage/cid/bafy...prop039-exec',
    block: 12_485_001,
  },
  {
    id: 'evt-173',
    type: 'RulesUpdated',
    timestamp: '2026-05-01T18:33:40Z',
    relativeTime: '1d ago',
    actor: { kind: 'multisig', label: 'Governance', ens: 'governance.aicouncil.eth' },
    title: 'Council Rules v0.4 deployed',
    summary: 'Soft cap raised: 5% → 7% per protocol. Hard cap unchanged at 15%.',
    delta: { kind: 'rules', value: 'v0.3 → v0.4' },
    txHash: '0x5e3a...b8d4',
    txUrl: 'https://sepolia.basescan.org/tx/0x5e3a...b8d4',
    cid: 'bafy...rules-v04',
    cidUrl: 'https://0g.ai/storage/cid/bafy...rules-v04',
  },
  {
    id: 'evt-172',
    type: 'RulesProposed',
    timestamp: '2026-05-01T17:12:08Z',
    relativeTime: '1d ago',
    actor: { kind: 'wallet', label: 'maxima.aicouncil.eth', ens: 'maxima.aicouncil.eth' },
    title: 'Rules update v0.4 proposed',
    summary: 'Justification: market conditions, recent verdicts trending toward soft-cap rejections.',
    delta: { kind: 'rules', value: 'v0.4 draft' },
    cid: 'bafy...rules-v04-draft',
    cidUrl: 'https://0g.ai/storage/cid/bafy...rules-v04-draft',
  },
  {
    id: 'evt-171',
    type: 'AgentAdded',
    timestamp: '2026-04-28T09:45:22Z',
    relativeTime: '4d ago',
    actor: { kind: 'wallet', label: 'pico.aicouncil.eth', ens: 'pico.aicouncil.eth' },
    title: 'Agent added: Sentiment',
    summary: 'LLM: Claude Sonnet 4.6, weight 0.8, trust gate 70%.',
    delta: { kind: 'agent', value: '+sentiment' },
    txHash: '0xa1b2...c3d4',
    txUrl: 'https://sepolia.basescan.org/tx/0xa1b2...c3d4',
    cid: 'bafy...agent-sentiment-add',
    cidUrl: 'https://0g.ai/storage/cid/bafy...agent-sentiment-add',
  },
];

// Statystyki dla top bar
const AUDIT_STATS = {
  total: 187,
  last24h: 23,
  proposals: 42,
  executions: 28,
  agents: 5,
  cidRegistered: '0G Storage',
  archiveSize: '4.2 MB',
};

// Filtry chipy
const AUDIT_FILTERS = [
  { id: 'all', label: { en: 'All events', pl: 'Wszystkie' }, count: 187 },
  { id: 'proposals', label: { en: 'Proposals', pl: 'Wnioski' }, count: 42, types: ['ProposalCreated'] },
  { id: 'votes', label: { en: 'Agent votes', pl: 'Głosy agentów' }, count: 84, types: ['AgentVoted'] },
  { id: 'verdicts', label: { en: 'Verdicts', pl: 'Werdykty' }, count: 21, types: ['VerdictReached'] },
  { id: 'executions', label: { en: 'On-chain executions', pl: 'Egzekucje on-chain' }, count: 28, types: ['OnchainExecuted', 'TimelockQueued', 'MultisigSigned'] },
  { id: 'rules', label: { en: 'Rules changes', pl: 'Zmiany zasad' }, count: 7, types: ['RulesUpdated', 'RulesProposed'] },
  { id: 'agents', label: { en: 'Agent lifecycle', pl: 'Cykl życia agentów' }, count: 5, types: ['AgentAdded', 'AgentReputationChanged'] },
];

// Event type kolory + ikony
const AUDIT_TYPE_META = {
  ProposalCreated:        { color: 'oklch(0.74 0.15 245)', icon: '◇', label: 'Proposal' },
  AgentVoted:             { color: 'oklch(0.78 0.14 75)',  icon: '◉', label: 'Vote' },
  VerdictReached:         { color: 'oklch(0.74 0.16 152)', icon: '✓', label: 'Verdict' },
  MultisigSigned:         { color: 'oklch(0.74 0.16 152)', icon: '⊕', label: 'Sig' },
  TimelockQueued:         { color: 'oklch(0.78 0.14 75)',  icon: '⊠', label: 'Queue' },
  OnchainExecuted:        { color: 'oklch(0.74 0.16 152)', icon: '◆', label: 'Execute' },
  RulesUpdated:           { color: 'oklch(0.74 0.16 305)', icon: '⚙', label: 'Rules' },
  RulesProposed:          { color: 'oklch(0.74 0.16 305)', icon: '◇', label: 'Rules' },
  AgentAdded:             { color: 'oklch(0.74 0.15 245)', icon: '+', label: 'Agent' },
  AgentReputationChanged: { color: 'oklch(0.66 0.014 255)',icon: '∆', label: 'Rep' },
};

const AUDIT_DATA = {
  events: AUDIT_EVENTS,
  stats: AUDIT_STATS,
  filters: AUDIT_FILTERS,
  typeMeta: AUDIT_TYPE_META,
};

window.AUDIT_DATA = AUDIT_DATA;
