// Component 4: Treasury Dashboard — data layer.
// Active positions, recent verdicts, activity feed, runway/yield metrics.

const DASH_TREASURY = {
  totalUsd: 1062184,
  delta7dUsd: 12840,        // +$12,840 last 7d
  delta7dPct: 1.22,
  netApy: 2.94,             // weighted avg APY across all positions (incl idle = 0)
  runwayMonths: 38,         // est months at current burn rate
  burnMonthlyUsd: 27800,
  yieldEarnedUsd: 4180,     // ytd
  riskScore: 'B+',          // composite — Low/Med-Low/Medium/etc, but display compact
};

// Allocation across positions + idle. Sums to DASH_TREASURY.totalUsd.
const DASH_ALLOCATION = [
  { id: 'aave',     label: 'Aave v3',    asset: 'mUSDC', usd: 50000,   pct: 4.71,  apy: 4.7,  color: 'oklch(0.74 0.16 245)', sinceDays: 12, contractShort: '0xae...3f1c', kind: 'deposit' },
  { id: 'compound', label: 'Compound',   asset: 'mUSDC', usd: 30000,   pct: 2.82,  apy: 3.8,  color: 'oklch(0.74 0.16 152)', sinceDays: 24, contractShort: '0xc3...e4b2', kind: 'deposit' },
  { id: 'idle',     label: 'Idle',       asset: 'mUSDC', usd: 979372,  pct: 92.20, apy: 0.0,  color: 'oklch(0.46 0.020 255)', sinceDays: null, contractShort: null,           kind: 'idle' },
  { id: 'eth',      label: 'ETH spot',   asset: 'ETH',   usd: 2812,    pct: 0.27,  apy: 0.0,  color: 'oklch(0.70 0.10 280)', sinceDays: null, contractShort: null,           kind: 'spot' },
];

// Recent verdicts — last N proposals, in reverse chronological order.
// status: 'approved' | 'rejected' | 'pending' | 'split' (no consensus) | 'executing'
const DASH_VERDICTS = [
  { id: 'PROP-042', title: { en: 'Allocate 100k USDC → Aave v3', pl: 'Wploc 100k USDC → Aave v3' }, status: 'pending',  tally: { for: 0, against: 0, abstain: 0 }, when: { en: 'now',         pl: 'teraz'      }, amountUsd: 100000, archived: false },
  { id: 'PROP-041', title: { en: 'Allocate 50k USDC → Aave v3',  pl: 'Wploc 50k USDC → Aave v3'  }, status: 'approved', tally: { for: 4, against: 0, abstain: 1 }, when: { en: '12d ago',     pl: '12d temu'   }, amountUsd: 50000,  archived: true,  cidShort: 'bafy...q4hzx' },
  { id: 'PROP-040', title: { en: 'Allocate 30k USDC → Compound', pl: 'Wploc 30k USDC → Compound' }, status: 'approved', tally: { for: 3, against: 1, abstain: 1 }, when: { en: '24d ago',     pl: '24d temu'   }, amountUsd: 30000,  archived: true,  cidShort: 'bafy...m81rv' },
  { id: 'PROP-039', title: { en: 'Swap 0.5 ETH → USDC',           pl: 'Wymień 0,5 ETH → USDC'      }, status: 'rejected', tally: { for: 1, against: 4, abstain: 0 }, when: { en: '31d ago',     pl: '31d temu'   }, amountUsd: 1675,   archived: true,  cidShort: 'bafy...j77kc' },
  { id: 'PROP-038', title: { en: 'Grant payout · core team Q1',   pl: 'Wypłata grantu · zespol Q1' }, status: 'split',    tally: { for: 2, against: 2, abstain: 1 }, when: { en: '38d ago',     pl: '38d temu'   }, amountUsd: 18000,  archived: true,  cidShort: 'bafy...d92xs' },
];

// Activity feed — terminal-style. Most recent first.
// type: 'vote' | 'proposal' | 'exec' | 'archive' | 'rule' | 'agent'
const DASH_ACTIVITY = [
  { ts: 'T-0s',        type: 'proposal', actor: 'treasury.aicouncil.eth', en: 'submitted PROP-042', pl: 'zlozyl PROP-042', detail: { en: '100k USDC → Aave v3',         pl: '100k USDC → Aave v3' } },
  { ts: 'T-12d',       type: 'archive',  actor: '0g.storage',             en: 'archived PROP-041',  pl: 'zarchiwizowal PROP-041', detail: { en: 'CID bafy...q4hzx',       pl: 'CID bafy...q4hzx' } },
  { ts: 'T-12d',       type: 'exec',     actor: 'treasury.aicouncil.eth', en: 'executed PROP-041',  pl: 'wykonal PROP-041', detail: { en: '50k USDC → aUSDC · 0.04 USDC gas', pl: '50k USDC → aUSDC · 0.04 USDC gas' } },
  { ts: 'T-12d',       type: 'vote',     actor: 'bull.aicouncil.eth',     en: 'voted FOR on PROP-041', pl: 'głos ZA na PROP-041', detail: { en: 'conf 0.84',       pl: 'konw 0,84' } },
  { ts: 'T-12d',       type: 'vote',     actor: 'risk.aicouncil.eth',     en: 'voted FOR on PROP-041', pl: 'głos ZA na PROP-041', detail: { en: 'conf 0.66',       pl: 'konw 0,66' } },
  { ts: 'T-12d',       type: 'vote',     actor: 'tech.aicouncil.eth',     en: 'voted FOR on PROP-041', pl: 'głos ZA na PROP-041', detail: { en: 'conf 0.78',       pl: 'konw 0,78' } },
  { ts: 'T-12d',       type: 'vote',     actor: 'sentiment.aicouncil.eth', en: 'voted FOR on PROP-041', pl: 'głos ZA na PROP-041', detail: { en: 'conf 0.59', pl: 'konw 0,59' } },
  { ts: 'T-12d',       type: 'vote',     actor: 'bear.aicouncil.eth',     en: 'voted ABSTAIN on PROP-041', pl: 'głos WSTRZ. na PROP-041', detail: { en: 'soft-cap waiver', pl: 'waiver soft-capa' } },
  { ts: 'T-12d',       type: 'rule',     actor: 'rules.aicouncil.eth',    en: 'flagged soft cap',   pl: 'oznaczyl soft cap', detail: { en: '4.7% > 5% soft (within hard 15%)', pl: '4,7% > 5% soft (w hard 15%)' } },
  { ts: 'T-12d',       type: 'proposal', actor: 'treasury.aicouncil.eth', en: 'submitted PROP-041', pl: 'zlozyl PROP-041', detail: { en: '50k USDC → Aave v3',          pl: '50k USDC → Aave v3' } },
  { ts: 'T-24d',       type: 'archive',  actor: '0g.storage',             en: 'archived PROP-040',  pl: 'zarchiwizowal PROP-040', detail: { en: 'CID bafy...m81rv',       pl: 'CID bafy...m81rv' } },
  { ts: 'T-24d',       type: 'exec',     actor: 'treasury.aicouncil.eth', en: 'executed PROP-040',  pl: 'wykonal PROP-040', detail: { en: '30k USDC → cUSDC',                pl: '30k USDC → cUSDC' } },
  { ts: 'T-31d',       type: 'archive',  actor: '0g.storage',             en: 'archived PROP-039',  pl: 'zarchiwizowal PROP-039', detail: { en: 'rejected · CID bafy...j77kc', pl: 'odrzucony · CID bafy...j77kc' } },
];

// 7d sparkline points for total treasury value (USD), normalized 0..1 inside renderer.
const DASH_SPARK_TREASURY = [1049344, 1051120, 1048990, 1054800, 1058450, 1057210, 1062184];
// 7d sparkline points for net APY (weighted)
const DASH_SPARK_APY = [2.61, 2.78, 2.81, 2.94, 2.94, 2.94, 2.94];

// i18n additions specific to dashboard.
const DASH_I18N = {
  en: {
    dashTitle: 'Treasury',
    dashSubtitle: 'AI Treasury Council · Base Sepolia',
    nav: { home: 'Dashboard', proposals: 'Proposals', positions: 'Positions', agents: 'Agents', rules: 'Rules', activity: 'Activity' },
    kpiTotalValue: 'Total value',
    kpiNetApy: 'Net APY',
    kpiIdle: 'Idle',
    kpiRunway: 'Runway',
    kpiYieldYtd: 'Yield · YTD',
    kpiRisk: 'Risk score',
    months: 'mo',
    wow: 'wow',
    weighted: 'weighted',
    allocation: 'Allocation',
    activePositions: 'Active positions',
    deposit: 'Deposit',
    spot: 'Spot',
    idleLabel: 'Idle (no yield)',
    sinceDays: 'since',
    daysShort: 'd',
    apy: 'APY',
    of: 'of',
    treasury: 'treasury',
    liveCouncil: 'Live Council',
    councilIdle: 'Council idle',
    awaitingProposal: 'Awaiting next proposal',
    conveneNow: 'Convene now',
    liveDebate: 'Live debate',
    activeNow: 'Active now',
    debating: 'Debating',
    elapsed: 'Elapsed',
    eta: 'Est',
    remaining: 'remaining',
    online: 'online',
    quickPropose: 'Quick propose',
    quickProposeHint: 'Plain language. AI parses, rules validate, council debates.',
    proposeButton: 'Convene Council',
    recentVerdicts: 'Recent verdicts',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
    statusSplit: 'No consensus',
    statusPending: 'Pending',
    statusExecuting: 'Executing',
    archivedTo: 'Archived to 0G',
    notArchived: 'Not archived',
    activityFeed: 'Activity',
    filterAll: 'All',
    filterApproved: 'Approved',
    filterRejected: 'Rejected',
    filterPending: 'Pending',
    agentsOnline: 'Agents',
    accuracy: 'Acc',
    statementsShort: 'stmts',
    walletConnected: 'Wallet',
    networkLabel: 'Network',
    blockShort: 'block',
    gas: 'Gas',
    storage: 'Storage',
    healthy: 'Healthy',
    proposalsTotal: 'Proposals',
    approvalRate: 'Approval rate',
    avgDebate: 'Avg debate',
    seconds: 's',
    emptyTitle: 'New treasury',
    emptyHint: 'Fund the treasury to begin. Once funded, you can submit your first proposal and the council will convene.',
    fundTreasury: 'Fund treasury',
    importMultisig: 'Import multisig',
    notFinAdvice: 'Not financial advice. Mock data, Base Sepolia.',
    txExecuting: 'Tx executing',
    txConfirmed: 'Tx confirmed',
    viewExplorer: 'View on explorer',
    archiveStatus: 'Archive status',
    expandDebate: 'Open full debate',
    minimize: 'Minimize',
  },
  pl: {
    dashTitle: 'Skarbiec',
    dashSubtitle: 'AI Treasury Council · Base Sepolia',
    nav: { home: 'Pulpit', proposals: 'Propozycję', positions: 'Pozycje', agents: 'Agenci', rules: 'Zasady', activity: 'Aktywność' },
    kpiTotalValue: 'Wartość skarbca',
    kpiNetApy: 'Net APY',
    kpiIdle: 'Bezczynne',
    kpiRunway: 'Runway',
    kpiYieldYtd: 'Zysk · YTD',
    kpiRisk: 'Ocena ryzyka',
    months: 'mies',
    wow: 't/t',
    weighted: 'ważone',
    allocation: 'Alokacja',
    activePositions: 'Aktywne pozycje',
    deposit: 'Depozyt',
    spot: 'Spot',
    idleLabel: 'Bezczynne (brak zysku)',
    sinceDays: 'od',
    daysShort: 'd',
    apy: 'APY',
    of: 'z',
    treasury: 'skarbca',
    liveCouncil: 'Rada na żywo',
    councilIdle: 'Rada nieaktywna',
    awaitingProposal: 'Oczekiwanie na kolejną propozycję',
    conveneNow: 'Zwolaj teraz',
    liveDebate: 'Debata na żywo',
    activeNow: 'Aktywne teraz',
    debating: 'Debata w toku',
    elapsed: 'Czas',
    eta: 'Ok.',
    remaining: 'pozostało',
    online: 'online',
    quickPropose: 'Szybka propozycja',
    quickProposeHint: 'Prostym językiem. AI parsuje, zasady walidują, rada debatuje.',
    proposeButton: 'Zwolaj Radę',
    recentVerdicts: 'Ostatnie werdykty',
    statusApproved: 'Przyjeto',
    statusRejected: 'Odrzucono',
    statusSplit: 'Brak konsensusu',
    statusPending: 'W toku',
    statusExecuting: 'Wykonywanie',
    archivedTo: 'Zarchiwizowano w 0G',
    notArchived: 'Nie zarchiwizowano',
    activityFeed: 'Aktywność',
    filterAll: 'Wszystkie',
    filterApproved: 'Przyjete',
    filterRejected: 'Odrzucone',
    filterPending: 'W toku',
    agentsOnline: 'Agenci',
    accuracy: 'Trafn',
    statementsShort: 'wyp',
    walletConnected: 'Portfel',
    networkLabel: 'Siec',
    blockShort: 'blok',
    gas: 'Gas',
    storage: 'Storage',
    healthy: 'OK',
    proposalsTotal: 'Propozycję',
    approvalRate: 'Wsk. przyjec',
    avgDebate: 'Sr. debata',
    seconds: 's',
    emptyTitle: 'Nowy skarbiec',
    emptyHint: 'Zasil skarbiec by rozpoczac. Po zasileniu można złożyć pierwsza propozycję a rada zostanie zwolana.',
    fundTreasury: 'Zasil skarbiec',
    importMultisig: 'Importuj multisig',
    notFinAdvice: 'To nie porada finansowa. Dane testowe, Base Sepolia.',
    txExecuting: 'Tx wykonywany',
    txConfirmed: 'Tx potwierdzony',
    viewExplorer: 'Zobacz w explorerze',
    archiveStatus: 'Status archiwum',
    expandDebate: 'Pełna debata',
    minimize: 'Zminimalizuj',
  },
};

// Aggregate stats derived from DASH_VERDICTS.
const DASH_STATS = {
  proposalsTotal: 42,
  approvalRate: 0.71,            // 30/42
  avgDebateSeconds: 28.4,
};

Object.assign(window, {
  DASH_TREASURY,
  DASH_ALLOCATION,
  DASH_VERDICTS,
  DASH_ACTIVITY,
  DASH_SPARK_TREASURY,
  DASH_SPARK_APY,
  DASH_I18N,
  DASH_STATS,
});
